version: "3.3"

services:
  db:
    container_name: "postgres-cr"
    restart: "always"
    build:
      context: ./
      dockerfile: postgres/postgres.Dockerfile
    volumes:
      - ./postgres/postgres.conf:/etc/postgresql/postgresql.conf
      - ./${VOLUMES}/postgres/postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    container_name: "api-cr"
    restart: "always"
    build:
      context: ./
      dockerfile: api/api.Dockerfile
    expose:
      - "5007"
    ports:
      - "5007:5007"
    env_file:
      - .env
    depends_on:
      - db

  crawler:
    container_name: "crawler-cr"
    build:
      context: ./
      dockerfile: crawler/crawler.Dockerfile
    command: bash -c "ls && envsubst < env.scrapy.cfg > scrapy.cfg && scrapyd"
    volumes:
      - ./${VOLUMES}/crawler:/var/crawler
    ports:
      - "6801:6801"
    tty: true
    stdin_open: true
    dns:
      - 8.8.8.8
    env_file:
      - .env
    depends_on:
      - db
      - backend
